[package]
name = "alti-gui-wifi"
version = "0.1.0"
edition = "2021"

[lib]
name = "app"
path = "src/lib.rs"

[[bin]]
name = "PokeIpGo"
path = "src/bin/app.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[web]]
name = "PokeIpWeb"
path = "src/main.rs" # we're using trunk, which uses main.rs only

[dependencies]
anyhow = "1.0.52"
pretty_env_logger = "0.4.0"
tokio = { version = "1.25", features = ["full"] }
dioxus = { version = "0.3.1" }
dioxus-desktop = "0.3.0"
wifiscanner = "0.5.1"
futures-channel = "0.3.19"
futures = "0.3.19"
reqwest = { version = "0.11", features = ["json"]}
serde_json = "1"
serde = "1"
rand = "0.8"
rustemon = "3.1"
lazy_static = "1.4"
bytemuck = "1.13"
rand_chacha = "0.3.1"
