[build]
target = 'x86_64-unknown-linux-gnu'
[target.aarch64-linux-android]
ar = '/mnt/c/dev/alti-gui-wifi/deps/android-ndk-r22b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar'
linker = '/mnt/c/dev/alti-gui-wifi/deps/android-ndk-r22b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang'
rustflags = [
    '-Clink-arg=-landroid',
    '-Clink-arg=-llog',
    '-Clink-arg=-lOpenSLES',
]

[target.armv7-linux-androideabi]
ar = '/mnt/c/dev/alti-gui-wifi/deps/android-ndk-r22b/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar'
linker = '/mnt/c/dev/alti-gui-wifi/deps/android-ndk-r22b/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi24-clang'
rustflags = [
    '-Clink-arg=-landroid',
    '-Clink-arg=-llog',
    '-Clink-arg=-lOpenSLES',
]

[target.i686-linux-android]
ar = '/mnt/c/dev/alti-gui-wifi/deps/android-ndk-r22b/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android-ar'
linker = '/mnt/c/dev/alti-gui-wifi/deps/android-ndk-r22b/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android24-clang'
rustflags = [
    '-Clink-arg=-landroid',
    '-Clink-arg=-llog',
    '-Clink-arg=-lOpenSLES',
]

[target.x86_64-linux-android]
ar = '/mnt/c/dev/alti-gui-wifi/deps/android-ndk-r22b/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-ar'
linker = '/mnt/c/dev/alti-gui-wifi/deps/android-ndk-r22b/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android24-clang'
rustflags = [
    '-Clink-arg=-landroid',
    '-Clink-arg=-llog',
    '-Clink-arg=-lOpenSLES',
]
